<?php

function notify($to,$data){

    $api_key="AAAAWFhy1n4:APA91bHDD6zjotHhPWMkn_7rsiRwjTawip2GZvF8nFA1qBIcrHp3XeQPqWKIbl8pi2LRxYNmrhimRUrMkj-23QqzTXQH0Q0hXbV4nNuuixFQjlPQdh8XVUkYzkXMpOWwNNGvrrKCtDVu";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

$to="/topics/alertasAtizapan"; #Firebase.messaging.subscribeTopic("alertasAtizapan")
$data=array(
    'title'=>'Alerta Atizapan',
    'body'=>$argv[1]
);

notify($to,$data);
echo "Notification Sent";

?>
